/**
 * THE Salaryman art bible.
 *
 * Every piece of in-game art (offices, bathrooms, props, buildings,
 * characters, UI illustrations) is generated by Nano Banana and styled
 * through the helpers in this file. There is intentionally ONE style
 * description — change it here and the entire game's look re-bakes.
 *
 * Style: a physical 1970s–1980s solar-punk world whose dark noir comes from
 * power, weather, wear, and neglect. Human-scale civic materials, plants,
 * repaired surfaces, analog machinery, and readable isometric silhouettes.
 */

import { generateImage, type AspectRatio, type GenerateImageResult, type Resolution } from "./nano-banana";

export const SALARYMAN_STYLE = [
  "Salaryman game art style: physical 1970s–1980s solar-punk retrofuture with human-scale civic architecture and repairable analog technology.",
  "Warm daylight, abundant plants, amber glass, painted steel, wood, brushed metal, paper, wired phones, switches, hand tools, and modular construction.",
  "Chunky readable pixel silhouettes or grounded production forms, crisp edges, restrained texture, no disposable detail.",
  "Dark noir comes from weather, framing, selective shadow, faded maintenance, and political pressure — not from changing every material to cyberpunk.",
  "No holograms, glowing circuitry, drones, neon sludge, impossible architecture, baked text, watermarks, or UI overlays.",
].join(" ");

/** Compose the final Nano Banana prompt for a Salaryman asset. */
export function composeSalarymanPrompt(subject: string, extras?: string): string {
  return [subject.trim(), extras?.trim(), SALARYMAN_STYLE].filter(Boolean).join(" ");
}

// ── Realistic character-template style ───────────────────────────────────────
// The intake "PICK YOUR LOOK" gallery shows ready-made REALISTIC characters
// (rendered through the Unreal node) so the player picks a believable avatar
// instead of building a pixel paper-doll. This is a deliberate, documented
// exception to the single pixel SALARYMAN_STYLE: character templates are meant
// to read as real people / lifelike androids. The style is still 100% backend
// AGNOSTIC — the composed prompt is stored verbatim and handed to whichever
// backend runs (Unreal, Blender, or a hosted image backend) with NO per-backend styling,
// preserving the "every backend renders the same prompt" invariant.
export const REALISTIC_CHARACTER_STYLE = [
  "Photorealistic cinematic character render, Unreal Engine 5 / AAA-game quality, ultra-detailed.",
  "Set in a physical solar-punk civic world under dark noir pressure: a real human posing for an identity portrait.",
  "Three-quarter upper-body framing, eye-level, sharp focus on the face, shallow depth of field, subtle film grain.",
  "Warm amber daylight with selective deep shadow and muted civic colors; noir comes from framing and weather rather than neon technology.",
  "Realistic skin texture, realistic fabric and materials, natural anatomy, filmic colour grade.",
  "Single subject centred, no text, no watermark, no UI overlays, no border.",
].join(" ");

/** Compose the final prompt for a REALISTIC character-template portrait. */
export function composeRealisticCharacterPrompt(subject: string): string {
  return [subject.trim(), REALISTIC_CHARACTER_STYLE].filter(Boolean).join(" ");
}

// ── Character-template catalog ───────────────────────────────────────────────
// Ready-made REALISTIC avatars offered on the intake identity step, one per
// archetype × faction (3 × 3 = 9). Picking one sets the player's portrait AND
// the matching underlying pixel-sprite appearance (the `look` hints + the
// client's faction-garb table) so the 2D world sprite stays consistent.
//
// `archetype` mirrors the client CharacterTemplate ('man' | 'woman' |
// 'replicant') and `faction` the client Faction ('suit' | 'nomad' |
// 'replicant'); the client derives body gender + faction garb from them. The
// `look` hints are hex/ids drawn from the client's APPEARANCE_* palettes so the
// pixel doll resembles the rendered portrait.
export type CharacterArchetype = "man" | "woman" | "replicant";
export type CharacterFaction = "suit" | "nomad" | "replicant";

export interface CharacterTemplateLook {
  skinTone: string;  // hex
  hairColor: string; // hex
  hairStyle: string; // APPEARANCE_HAIR_STYLES id
  faceStyle: string; // APPEARANCE_FACE_STYLES id
  outfitStyle?: string;
  outfitColor?: string;
}

export interface CharacterTemplateDef {
  id: string;        // art key (also the template id)
  label: string;
  archetype: CharacterArchetype;
  faction: CharacterFaction;
  subject: string;   // realistic portrait description
  look: CharacterTemplateLook;
}

const CHARACTER_TEMPLATE_BASE_CATALOG: CharacterTemplateDef[] = [
  {
    id: "char_template_man_suit",
    label: "Corporate Salaryman",
    archetype: "man",
    faction: "suit",
    subject:
      "A weary middle-aged corporate salaryman in a crisp charcoal pinstripe suit and thin dark tie, short neatly-combed black hair, clean-shaven, fair skin, a tired but determined expression.",
    look: { skinTone: "#e8c4a0", hairColor: "#0a0a0a", hairStyle: "short", faceStyle: "plain" },
  },
  {
    id: "char_template_man_nomad",
    label: "Wasteland Drifter",
    archetype: "man",
    faction: "nomad",
    subject:
      "A rugged wastelander man in a worn leather duster over a dust-stained shirt, short messy dark-brown hair, a stubble beard, weathered tan skin, a faded bandana at his neck, hard street-smart stare.",
    look: { skinTone: "#d4a878", hairColor: "#2a1808", hairStyle: "short", faceStyle: "beard" },
  },
  {
    id: "char_template_man_replicant",
    label: "Off-Grid Operative",
    archetype: "man",
    faction: "replicant",
    subject:
      "An off-grid male android passing as human, in a sleek synth jumpsuit, pale synthetic-grey skin with faint subdermal cyan circuit lines along the jaw, a slim optical visor over the eyes, a platinum buzz cut, eerily calm.",
    look: { skinTone: "#9cb4c0", hairColor: "#e8e4d8", hairStyle: "buzz", faceStyle: "visor" },
  },
  {
    id: "char_template_woman_suit",
    label: "Corporate Salarywoman",
    archetype: "woman",
    faction: "suit",
    subject:
      "A poised corporate salarywoman in a tailored navy business dress and blazer, long dark hair pulled back, fair skin, subtle makeup, a composed confident expression.",
    look: { skinTone: "#e8c4a0", hairColor: "#2a1808", hairStyle: "long", faceStyle: "plain" },
  },
  {
    id: "char_template_woman_nomad",
    label: "Wasteland Runner",
    archetype: "woman",
    faction: "nomad",
    subject:
      "A tough wasteland courier woman in a long weathered trench coat over utility gear, bronze sun-worn skin, auburn hair in a high ponytail, a thin scar across one cheek, fierce alert eyes.",
    look: { skinTone: "#b07848", hairColor: "#7a3a18", hairStyle: "ponytail", faceStyle: "scar" },
  },
  {
    id: "char_template_woman_replicant",
    label: "Off-Grid Specialist",
    archetype: "woman",
    faction: "replicant",
    subject:
      "An off-grid female android in a form-fitting ice-grey synth jumpsuit, smooth pale-violet synthetic skin, a faint glowing cyan iris ring, a sleek teal bob, a serene unreadable face.",
    look: { skinTone: "#c8c4d0", hairColor: "#2acccc", hairStyle: "bowl", faceStyle: "cyber" },
  },
  {
    id: "char_template_replicant_suit",
    label: "Corporate Android",
    archetype: "replicant",
    faction: "suit",
    subject:
      "A corporate-issue android in an immaculate steel-grey suit, brushed-metal synthetic skin with seamless panel lines, neutral androgynous features, a thin cyan status LED at the temple, perfectly still and poised.",
    look: { skinTone: "#9cb4c0", hairColor: "#9a9a9a", hairStyle: "short", faceStyle: "cyber" },
  },
  {
    id: "char_template_replicant_nomad",
    label: "Scavenger Unit",
    archetype: "replicant",
    faction: "nomad",
    subject:
      "A scavenged rogue android in a patched rust-coloured utility rig, a scuffed matte-grey chassis with exposed wiring at one shoulder, mismatched optics with one glowing pink eye, a short red mohawk, androgynous and defiant.",
    look: { skinTone: "#b8b0a8", hairColor: "#a83020", hairStyle: "mohawk", faceStyle: "cyber" },
  },
  {
    id: "char_template_replicant_replicant",
    label: "Free Synthetic",
    archetype: "replicant",
    faction: "replicant",
    subject:
      "A liberated free synthetic in a minimalist ice-white synth jumpsuit, luminous pale synthetic skin with soft glowing cyan circuit traces, a calm androgynous face, a smooth hairless head, an aura of quiet autonomy.",
    look: { skinTone: "#c8c4d0", hairColor: "#56e8ff", hairStyle: "bald", faceStyle: "visor" },
  },
];

// Three deterministic variations per archetype/faction keep the identity system
// deep without creating a second source of truth. The base 9 remain stable for
// old saves/art keys; variants add alternate hair/face/outfit language and an
// explicit outlander origin where the nomad faction already implies it.
const CHARACTER_VARIATION_LOOKS: CharacterTemplateLook[] = [
  { skinTone: "#d4a878", hairColor: "#7a3a18", hairStyle: "undercut", faceStyle: "shades" },
  { skinTone: "#8a5a3a", hairColor: "#c244aa", hairStyle: "afro", faceStyle: "freckles" },
];
export const CHARACTER_TEMPLATE_CATALOG: CharacterTemplateDef[] = CHARACTER_TEMPLATE_BASE_CATALOG.flatMap((template) => [
  template,
  ...CHARACTER_VARIATION_LOOKS.map((look, index) => ({
    ...template,
    id: `${template.id}_v${index + 2}`,
    label: `${template.label} · ${index === 0 ? "NIGHT SHIFT" : "WILD CARD"}`,
    subject: `${template.subject} Alternate identity variation ${index === 0 ? "with an undercut, tinted lenses and a late-shift utility layer" : "with expressive textured hair, visible freckles and a vivid custom outer layer"}.`,
    look: { ...template.look, ...look, outfitColor: index === 0 ? "#1a4a4a" : "#8a1e2a" },
  })),
]);

/** Build the kit entries for every character template (realistic, Unreal-routed). */
function characterTemplateKitEntries(): ArtKitEntry[] {
  return CHARACTER_TEMPLATE_CATALOG.map((t) => ({
    key: t.id,
    category: "character" as const,
    aspectRatio: "3:4" as const,
    backend: "unreal",
    jobType: "object" as const,
    subject: t.subject,
    fullPrompt: composeRealisticCharacterPrompt(t.subject),
  }));
}

export interface SalarymanArtOptions {
  aspectRatio?: AspectRatio;
  resolution?: Resolution;
  extras?: string;
  timeoutMs?: number;
}

/** Generate one piece of Salaryman art end-to-end (synchronous wrapper). */
export function generateSalarymanArt(subject: string, opts: SalarymanArtOptions = {}): Promise<GenerateImageResult> {
  return generateImage({
    prompt: composeSalarymanPrompt(subject, opts.extras),
    aspectRatio: opts.aspectRatio ?? "1:1",
    resolution: opts.resolution ?? "1K",
    outputFormat: "jpg",
    timeoutMs: opts.timeoutMs,
  });
}

// ── The Art Kit ────────────────────────────────────────────────────────────
// Predefined assets that the game pulls from /api/art/asset/:key.
// Add a key here, restart, and Nano Banana will bake it on first request.
//
// Categories:
//   scene     — full background scenes (16:9)
//   prop      — single objects centred on dark/empty bg (1:1)
//   building  — isometric buildings for the world map (4:3)
//   character — characters, 3/4 view portrait (3:4)
//   ui        — illustrations for menus / cards (16:9 or 1:1)

export type ArtCategory = "scene" | "prop" | "building" | "character" | "ui";

export interface ArtKitEntry {
  key: string;
  category: ArtCategory;
  subject: string;          // what to draw (style is appended automatically)
  aspectRatio: AspectRatio;
  /**
   * Optional preferred render backend (provider id, e.g. "unreal"). When set,
   * the pipeline routes this asset to that backend if it's configured, and
   * If set, the asset is pinned to this renderer. An unavailable explicit
   * backend is a hard failure; it must never silently change the asset's look.
   * Left unset, the asset uses the default backend.
   */
  backend?: string;
  /**
   * Optional render-recipe hint, only honored by the Unreal node (object /
   * landscape / cinematic). Hosted image backends ignore it.
   */
  jobType?: "object" | "landscape" | "cinematic";
  /**
   * Optional FULLY-composed prompt. When set, the pipeline stores it verbatim
   * (instead of composeSalarymanPrompt(subject)) so an asset can opt out of the
   * pixel SALARYMAN_STYLE — e.g. the realistic character templates. It is still
   * backend-agnostic: the same stored prompt is handed to whichever backend runs.
   */
  fullPrompt?: string;
}

export const SALARYMAN_ART_KIT: ArtKitEntry[] = [
  // ── Scenes ──────────────────────────────────────────────────────────────
  {
    key: "scene_bathroom",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide isometric interior of a dingy fluorescent corporate bathroom on the 12th floor. Two porcelain sinks on the left wall under a cracked mirror, a wall-mounted hand dryer in the centre, two stalls on the right, a single open exit door on the far right glowing faintly pink from the hallway beyond. Wet tile floor catching neon reflections.",
  },
  {
    key: "scene_office",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide isometric interior of a small one-person corporate office. A desk with a computer monitor and a desk lamp casting cyan light, a leather chair, a filing cabinet, a potted dead plant, and a glowing pink terminal kiosk in the back-right corner. Three vertical bot cryo-tubes line the left wall, soft cyan condensation drifting from them.",
  },
  {
    key: "scene_lobby",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide isometric corporate tower lobby at night. Reception desk with a single bored receptionist, brass elevator doors, marble floor reflecting hot pink neon signage that reads abstract glyphs, a security turnstile, rain visible through tall windows behind.",
  },
  {
    key: "scene_pablo_terminal",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide isometric view of a single glowing pink computer terminal kiosk in a dark room. The screen emits a swirling magenta nebula. A leather chair sits in front of it. Scattered cables, a coffee mug, and a phone on the desk. Empty otherwise.",
  },
  {
    key: "scene_nebula",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Cosmic Pablo Nebula: a swirling pink and cyan nebula in deep space, a single vague humanoid silhouette dissolving into stars at the centre. Particles, dust, distant galaxies. No text.",
  },
  {
    key: "scene_wakeup",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide isometric interior of a cramped corporate office cubicle in the early morning. A salaryman in a rumpled shirt is slumped face-down asleep on the desk, drooling on scattered papers, one arm dangling. A retro alarm clock on the desk is mid-ring, vibrating with little motion lines, its red digits glowing. A dark computer monitor and a desk lamp sit beside him. Harsh pale dawn light spills through vertical blinds on the left, cutting bright bars across the desk. A coffee mug tipped over, a sticky note stuck to the monitor. The mood is 'overslept, late for work'. Hot pink and cyan neon glow from the hallway beyond. Cyberpunk noir pixel-painting, cinematic, dark navy shadows, no text.",
  },
  {
    key: "city_minx_city",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic establishing shot of MINX CITY, a neon-drenched corporate megacity at night. A dense skyline of black PABLO CORP towers crowned with hot-pink and cyan holographic billboards, monorail cables crossing between buildings, rain-wet streets far below glowing with reflected neon, a single colossal corporate logo-spire dominating the centre, a sickly poison fog rolling across the wasteland beyond the city wall on the horizon. Cyberpunk noir, dark navy shadows, volumetric haze, no text, no characters.",
  },
  {
    key: "city_huda_city",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic establishing shot of HUDA CITY, PABLO CORP's rain-slick Asian capital at night. A humid monsoon megacity of stacked neon night markets and lantern-lit canals threading between tall tower-farms draped in glowing green vertical gardens, paper lanterns and jade and teal signage reflecting in wet streets, sampans and drones crowding the waterways, warm rain falling through the neon. Cyberpunk noir, teal and magenta palette, volumetric haze, dark shadows, no text, no characters.",
  },

  // ── Props ───────────────────────────────────────────────────────────────
  {
    key: "prop_sink",
    category: "prop",
    aspectRatio: "1:1",
    subject:
      "A single porcelain bathroom sink with a chrome faucet, isolated on a dark navy background. 3/4 view, slight cyan rim light from the right.",
  },
  {
    key: "prop_dryer",
    category: "prop",
    aspectRatio: "1:1",
    subject:
      "A wall-mounted white plastic hand dryer, isolated on a dark navy background. 3/4 view, soft pink LED indicator light.",
  },
  {
    key: "prop_door",
    category: "prop",
    aspectRatio: "1:1",
    subject:
      "A monumental sealed cyber-gateway portal viewed head-on, dead-centre composition. A massive black bezel framing a vertical hot-pink and cyan plasma membrane that ripples like liquid mercury, with prismatic color along the edges and fractured pixel fragments across the surface. Hot magenta neon trim around the bezel etching katakana-style runes, rivets glowing with embedded LEDs. Two enormous beams of light spill out of the seam where the door meets the floor, casting volumetric haze in the foreground. Akira-flavoured cyberpunk noir, hyper-detailed, cinematic key light from above, dark navy void background, no text, no characters, no UI overlay, the gateway fills 90 percent of the frame.",
  },
  {
    key: "prop_terminal_kiosk",
    category: "prop",
    aspectRatio: "1:1",
    subject:
      "A single chunky 8-bit computer terminal kiosk on a small podium. The screen glows hot pink and emits a tiny nebula. Isolated on dark navy background.",
  },
  {
    key: "prop_bot_tube",
    category: "prop",
    aspectRatio: "1:1",
    subject:
      "A single vertical glass cryo-tube containing a sleeping humanoid bot, lit from below with cyan light, soft condensation, isolated on dark navy background.",
  },
  {
    key: "prop_desk",
    category: "prop",
    aspectRatio: "1:1",
    subject:
      "A single corporate desk with a computer monitor showing a pink waveform, a desk lamp casting cyan light, a coffee mug, a stack of papers. Isolated on dark navy background.",
  },
  {
    key: "prop_filing_cabinet",
    category: "prop",
    aspectRatio: "1:1",
    subject:
      "A single tall four-drawer steel filing cabinet, scuffed paint, one drawer partly open with neon pink folders inside. Isolated on dark navy background.",
  },

  // ── Buildings (isometric for the world map) ─────────────────────────────
  {
    key: "building_office_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "Isometric exterior of a small two-storey corporate office building, flat roof, windows lit with cyan light, a single pink neon sign on the front. Floating on dark navy void.",
  },
  {
    key: "building_tower_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "Isometric exterior of a tall corporate skyscraper, ~30 storeys, dotted with lit cyan windows, hot pink antenna on top, faint clouds around the upper floors. Floating on dark navy void.",
  },
  {
    key: "building_kiosk_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "Isometric exterior of a small street-corner terminal kiosk shaped like a phone booth, glowing hot pink screen on the front. Floating on dark navy void.",
  },
  {
    key: "building_warehouse_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "Isometric exterior of a low-slung industrial warehouse with a corrugated metal roof, a roll-up loading door, cyan strip lights along the eaves. Floating on dark navy void.",
  },
  {
    key: "building_studio_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "Isometric exterior of a tiny one-room studio loft on top of a fire escape, single pink curtain in the window, hot pink potted plant on the balcony. Floating on dark navy void.",
  },

  // ── Characters ──────────────────────────────────────────────────────────
  {
    key: "char_pablo",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Three-quarter view portrait of Pablo, a sharply-dressed AI mogul in a black suit and pink turtleneck, slick black hair, calm confident expression, faint nebula glow around his head. Standing pose, dark navy background.",
  },
  {
    key: "char_jean_claw",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Three-quarter view portrait of Jean Claw, a hulking blue-collar bot with one massive industrial claw arm and one normal arm, dented yellow body plating, glowing cyan visor. Standing pose, dark navy background.",
  },
  {
    key: "char_salaryman",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Three-quarter view portrait of an unremarkable salaryman in a rumpled grey suit and white shirt, loosened tie, briefcase in one hand, faint exhausted expression. Standing pose, dark navy background.",
  },

  // ── UI illustrations ────────────────────────────────────────────────────
  {
    key: "ui_card_economy",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Illustration for an economy/finance menu card: a stylised bank vault door cracked open with hot pink florin coins spilling out, isometric view.",
  },
  {
    key: "ui_card_combat",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Illustration for a combat menu card: two silhouetted figures mid-fight in a neon alley, one swinging a katana, the other raising fists. Hot pink rim light.",
  },
  {
    key: "ui_card_realestate",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Illustration for a real-estate menu card: a hand holding a brass key over a tiny isometric office building, hot pink price tag floating above.",
  },

  // ── Cutscene character portraits ────────────────────────────────────────
  // High-detail pixel-art "talking head" frames used by the cutscene runner.
  // Portrait aspect, slight 3/4 turn, dramatic neon rim-lighting. The art
  // style suffix in buildPrompt() handles the "hand-painted pixel-art
  // 32-bit JRPG cutscene" anchor — every portrait stays consistent.
  {
    key: "cutscene_pablo",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Hyper-detailed pixel-art portrait of Pablo, AI mogul: chest-up, slight three-quarter turn to camera, sharp jawline, slick black hair, hot pink turtleneck under a black tailored blazer, single gold ring. Calm half-smile. A swirling pink-and-cyan nebula glows softly behind his head. Cinematic key light from camera-left, rim light from behind in cyan. Dialogue-frame composition with empty headroom on the right for a speech bubble.",
  },
  {
    key: "cutscene_mila",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Hyper-detailed pixel-art portrait of Mila, a free-thinking escaped replicant woman: chest-up, slight three-quarter turn to camera, late-20s, luminous teal-and-violet synthetic skin sheen, short tousled aqua-white hair with one strand breaking into loose pixels, faint hairline seams at the temple hinting she is artificial, alert hopeful eyes, a scuffed charcoal utility jacket over a teal tech-knit. A swirling aqua-and-violet nebula glows softly behind her head. Cool key light from camera-left, teal rim light from behind. Dialogue-frame composition with empty headroom on the right for a speech bubble.",
  },
  {
    key: "cutscene_jean_claw",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Hyper-detailed pixel-art portrait of Jean Claw, the office-manager bot: chest-up, slight three-quarter turn, hulking yellow-and-black industrial torso, one massive hydraulic claw raised at chest height, the other a normal four-fingered manipulator, glowing horizontal cyan visor, scuffed paint and oil streaks, condensation steam curling around shoulder vents. Background: a dim corporate hallway smeared with hot pink neon. Dialogue-frame composition.",
  },
  {
    key: "cutscene_receptionist",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Hyper-detailed pixel-art portrait of a bored corporate receptionist behind a marble lobby desk: chest-up, three-quarter view, late-30s, severe black bob haircut, headset on one ear, cyan blazer over a black blouse, faint dark circles under tired eyes, painted nails tapping a stack of folders. Behind her: a pink neon sign reading abstract glyphs and brass elevator doors. Dialogue-frame composition.",
  },
  {
    key: "cutscene_recruiter",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Hyper-detailed pixel-art portrait of a corporate recruiter: chest-up, three-quarter view, mid-30s, asymmetric short blonde haircut, magenta blazer with a sharp lapel, white silk shirt, holding a tablet showing a candidate dossier, pearl earrings catching cyan light. Background: a dim glass-walled conference room with a faint hot-pink whiteboard reflection. Dialogue-frame composition.",
  },
  {
    key: "cutscene_courier",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Hyper-detailed pixel-art portrait of a delivery courier: chest-up, three-quarter view, early-20s, faded purple bandana over braided hair, scratched cyan moto jacket with reflective tape, a stained delivery satchel strap across the chest, a small drone hovering at shoulder height with a glowing pink light. Background: a wet rooftop at night with city neon. Dialogue-frame composition.",
  },
  {
    key: "cutscene_banker",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Hyper-detailed pixel-art portrait of a private banker: chest-up, three-quarter view, late-50s, slicked silver hair, gold rim glasses, charcoal pinstripe three-piece suit with a hot-pink pocket square, gold tie-pin shaped like a coin, a glowing florin coin spinning between two fingers. Background: a vault door behind a velvet rope. Dialogue-frame composition.",
  },
  {
    key: "cutscene_lawyer",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Hyper-detailed pixel-art portrait of a corporate lawyer: chest-up, three-quarter view, early-40s, sharp dark bob with one streak of cyan, severe black power-suit with a high collar, single pearl earring, holding a leather portfolio under one arm, faint smirk. Background: floor-to-ceiling law-library bookshelves with a hot-pink desk lamp. Dialogue-frame composition.",
  },
  {
    key: "cutscene_player_default",
    category: "character",
    aspectRatio: "3:4",
    subject:
      "Hyper-detailed pixel-art portrait of a generic salaryman player avatar: chest-up, three-quarter turn AWAY from camera (over-the-shoulder framing, back partially to viewer, head turned to listen), rumpled grey suit jacket, loose black tie, faint cyan rim light along the shoulder. The face is mostly obscured. Background: out-of-focus office hallway with hot-pink neon. Dialogue-frame composition.",
  },

  // ── Bot assistants (pixel sprites that scurry inside a bot's office) ────
  // 4-frame walk/work cycles get baked from each of these; the AssistantPool
  // component just animates between idle/work poses derived from the same art.
  {
    key: "assistant_intern",
    category: "character",
    aspectRatio: "1:1",
    subject:
      "Pixel-art full-body sprite of a tiny office intern assistant: chibi proportions, oversized cyan dress shirt with rolled sleeves, black slacks, a stack of three colourful folders cradled to chest, harried expression, half-running pose. Dark navy isolated background, no shadow. Sharp pixel edges, vivid palette.",
  },
  {
    key: "assistant_pa",
    category: "character",
    aspectRatio: "1:1",
    subject:
      "Pixel-art full-body sprite of a tiny personal-assistant droid: chibi proportions, sleek white-and-pink chassis with a single glowing cyan eye on a swivel head, two thin manipulator arms holding a floating tablet, hovering on a tiny anti-grav disc above the floor. Dark navy isolated background. Sharp pixel edges.",
  },
  {
    key: "assistant_engineer",
    category: "character",
    aspectRatio: "1:1",
    subject:
      "Pixel-art full-body sprite of a tiny engineer-bot assistant: chibi proportions, scuffed orange jumpsuit, welding goggles pushed up on forehead, a sparking arc-welder in one hand and a wrench tucked in the belt. Dark navy isolated background, no shadow. Sharp pixel edges.",
  },

  // ── Storefronts & vending ──────────────────────────────────────────────
  {
    key: "vending_machine_iso",
    category: "ui",
    aspectRatio: "3:4",
    subject:
      "Front-facing pixel-art illustration of a tall corporate-issue bot vending machine: glossy magenta-and-black housing, six glass slots in a 3x2 grid each containing a different chibi office bot in a blister-pack capsule, glowing cyan price readout at the top reading abstract glyphs, big chrome dispense slot at the bottom, hot pink neon trim along the edges, sticker on the side reading 'FRESH BOTS'. Set against a dark navy void with a subtle pink floor reflection.",
  },
  {
    key: "bot_factory_storefront_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "Isometric pixel-art exterior of a downtown 'BOT FACTORY' storefront: two-storey shop, big plate-glass front window showing rows of chibi bots on shelves, hot-pink neon sign reading 'BOT FACTORY' over the door, a vending machine flanking the entrance, a tiny salaryman customer walking in. Floating on dark navy void.",
  },

  // ── Real-estate property templates (shown at the realty office & intro) ──
  {
    key: "property_loft",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of a tiny one-room studio loft apartment: brick wall, sunken floor with a pink futon, mini fridge, bathroom door, single window with neon city view. Furnished, lit, lived-in. Floating on dark navy void with a faint hot-pink price tag in the corner.",
  },
  {
    key: "property_corner_office",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of a corner-office on a high floor: floor-to-ceiling windows on two walls overlooking a neon city skyline, large executive desk with a glowing pink terminal, two leather chairs, a globe on a stand, framed art. Floating on dark navy void with a hot-pink price tag.",
  },
  {
    key: "property_warehouse",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of a converted industrial warehouse workspace: high ceiling with exposed pipes, big roll-up loading door, concrete floor with floor tape lanes, shelving units along one wall, a single pink-glowing forklift in the centre. Floating on dark navy void with a hot-pink price tag.",
  },
  {
    key: "property_penthouse",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of a penthouse executive suite: marble floor, sunken lounge with a hot-pink velvet couch, glass coffee table, full wet bar in cyan neon, panoramic window showing a low aerial city view, a private helipad just visible through the window. Floating on dark navy void with a hot-pink price tag.",
  },
  {
    key: "property_kiosk",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of a sidewalk terminal kiosk-shop: tiny single-room interior with one stool, one pink-screen terminal on a counter, a coffee thermos, a coat hook, a window facing the street. Floating on dark navy void with a hot-pink price tag.",
  },
  {
    key: "property_studio",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of a midtown studio apartment: real bedroom alcove with a bed, separate full bathroom door, kitchenette with a hot plate and mini-fridge, a desk nook with a single pink-screen terminal, one window with a noodle-cart neon sign visible through it. Floating on dark navy void with a faint hot-pink price tag in the corner.",
  },
  {
    key: "property_townhouse",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of a three-storey family townhouse: ground-floor garage with a small car, mid-floor living room with two networked pink terminals on a desk, top-floor bedrooms, a tiny back garden plot with a tree, front door with a brass number, neighbouring townhouses faintly silhouetted on either side. Floating on dark navy void with a hot-pink price tag.",
  },
  {
    key: "cover_hero",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cinematic pixel-art hero panel for the SALARYMAN platform: a lone salaryman in a black suit and red tie standing on a rain-slick neon street, briefcase in hand, looking up at a hot-pink towering skyline of corporate ziggurats and holographic ad-blimps, a tiny shiba-inu drone hovering at his shoulder, the words 'ATTENTION IS ALL YOU NEED' rendered subtly as floating neon kanji-style glyphs in the rain. Hot pink + cyan palette over deep navy. Retro 90s anime arcade vibe. Wide cinematic 16:9 framing.",
  },
  {
    key: "property_hq_tower",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of a corporate HQ floor in a glass tower: open-plan office with rows of desks (suggest 80 stations) lit by overhead pink and cyan strip lighting, a reception desk with a logo wall on the left, a glassed-in war room with a holo-map on the right, a server-closet door with blinking lights, panoramic windows showing a low aerial city view. Floating on dark navy void with a hot-pink price tag.",
  },
  // ── New tier set: entry-level apartment-office, mid-tier coworking,
  // mega-org HQ floor / private tower / corporate campus, plus the
  // ultra-elite SKY VILLA. All pure Akira-flavoured pixel art on dark navy.
  {
    key: "property_apartment_office",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of a small apartment-converted office on the 14th floor of a residential building (NOT the Shadow tower, an ordinary neighbouring block): three desks arranged against a window wall facing a neon city, two pink-glowing terminals, a kettle on a kitchenette counter, a shoe rack by the door, futon rolled up in the corner, residential hallway visible through a glass door. Akira-style hot pink + cyan over deep navy void with a faint price tag.",
  },
  {
    key: "property_coworking_suite",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of a glass-walled co-working suite inside a tower: eight modular desks in two rows, four pink-screen terminals, two soundproof phone booths against the back wall, a shared printer island, a small kitchen counter with espresso machine, a reception silhouette through the glass entry. Pink + cyan neon strip lighting. Akira flavour over deep navy void with a price tag.",
  },
  {
    key: "property_hq_floor",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of an entire corporate HQ floor in a glass tower: 120 desks in long rows under pink and cyan strip lighting, reception lobby with a logo wall on the left, eight glassed-in war rooms along the right wall (one with a holographic map), an on-site server-closet with blinking lights, panoramic windows showing aerial neon city view. Akira aesthetic over deep navy void with a price tag.",
  },
  {
    key: "property_tower",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art elevation of a privately-owned 12-storey corporate tower at night: glass-and-steel facade with hot-pink corporate logo near the top, lobby on the ground floor, cafeteria visible mid-tower, helipad with a parked helicopter on the roof, surrounding lower buildings, a slick rain-wet street at the base. Akira aesthetic, pink + cyan neon over deep navy void with a price tag.",
  },
  {
    key: "property_campus",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art aerial of a corporate campus: three matching glass towers arranged around a central koi-pond plaza with a small bridge, self-driving shuttle pods on tracks linking the towers, manicured trees, a perimeter wall, a sub-orbital landing pad on the largest tower's roof, hot-pink corporate logo banners. Akira aesthetic over deep navy void with a price tag.",
  },
  {
    key: "property_sky_villa",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Cutaway pixel-art illustration of an ultra-luxury sky villa above the cloud layer: panoramic floor-to-ceiling glass on every wall showing only clouds and sunset gradients, a sunken lounge with a hot-pink velvet sectional, an indoor onsen pool with steam rising, a private elevator door, a small drone bay with a parked delivery drone, screening room visible through an arch. Akira aesthetic, pink + cyan neon over deep navy void with a price tag.",
  },

  // ── WORLD REBUILD — the survivors of Minx City ──────────────────────────
  // After the bombing, only four landmark buildings + a campsite remain on the
  // corners of a single intersection. These are HIGH-FIDELITY, each visually
  // UNIQUE (never reuse a silhouette), drawn in a true 2:1 isometric projection
  // so the renderer can depth-sort them. The footprint sits on a small square
  // ground plinth so the sprite reads as "placed" on the world grid. Pure dark
  // navy void background (matches the world ambient) — no extra scenery.
  {
    key: "world_bank_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "True 2:1 isometric pixel-art of a single landmark building: MINX MUTUAL, a brutalist gold-vault bank shaped like a stepped ziggurat of black granite with thick hot-pink neon banding between each tier, a colossal circular brushed-gold vault door set into the front face glowing faint cyan, two squat pillars flanking a short entrance stair, a rooftop beacon pulsing pink. Heavy, squat, monumental. The building rests on a small square dark-stone isometric plinth. Centred, floating on a flat dark navy void. Sharp pixel edges, chunky 8-bit colour blocking, no text.",
  },
  {
    key: "world_tower_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "True 2:1 isometric pixel-art of a single landmark building: PABLO'S SHADOW TOWER, a slender obsidian-glass corporate spire that tapers as it rises, faceted mirror-black facade catching cyan reflections, thin vertical hot-pink light seams running its full height, and a crown at the very top that holds a swirling pink-and-cyan nebula orb radiating soft light. Tall and narrow, unmistakably the tallest survivor. The tower rests on a small square dark-stone isometric plinth. Centred, floating on a flat dark navy void. Sharp pixel edges, chunky 8-bit colour blocking, no text.",
  },
  {
    key: "world_factory_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "True 2:1 isometric pixel-art of a single landmark building: the BOT FACTORY, a wide low industrial assembly plant of riveted steel and corrugated panels, a saw-tooth north-light roof, two stubby smokestacks venting faint cyan steam, a glass-fronted showroom corner displaying chibi bots on shelves, a roll-up loading bay with a hot-pink 'FRESH BOTS' sign, an external conveyor belt curling around one side. Boxy, sprawling, mechanical. The plant rests on a small square dark-stone isometric plinth. Centred, floating on a flat dark navy void. Sharp pixel edges, chunky 8-bit colour blocking, no text.",
  },
  {
    key: "world_realty_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "True 2:1 isometric pixel-art of a single landmark building: the RECONSTRUCTION OFFICE, a civic art-deco hall of pale concrete with a stepped fluted facade, tall arched windows lit warm pink, a green-patina copper dome with a rotating cyan surveyor's beacon on top, a broad colonnaded entrance porch, and a small scaffold + crane arm attached to one flank signalling its rebuild authority. Stately, symmetrical, official. The hall rests on a small square dark-stone isometric plinth. Centred, floating on a flat dark navy void. Sharp pixel edges, chunky 8-bit colour blocking, no text.",
  },
  {
    key: "world_campsite_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "True 2:1 isometric pixel-art of a survivors' CAMPSITE: a loose ring of four patched canvas tents in faded teal and grey around a glowing orange barrel fire, a makeshift clothesline strung between two poles, stacked supply crates, a single salvaged road-sign post, scattered bedrolls. Humble, lived-in, the refuge of the broke and the displaced. The camp rests on a small square patch of cracked dark earth as an isometric plinth. Centred, floating on a flat dark navy void. Sharp pixel edges, chunky 8-bit colour blocking, no text.",
  },
  {
    key: "world_subway_station_iso",
    category: "building",
    aspectRatio: "4:3",
    subject:
      "True 2:1 isometric pixel-art of a SUBWAY STATION entrance: a chrome-and-glass canopy over a descending stairwell, a glowing hot-pink 'M' roundel sign on a post, a cyan-lit route-map panel beside the stairs, turnstile silhouettes just visible below, a vent grille exhaling faint steam. Compact transit kiosk. It rests on a small square paved isometric plinth. Centred, floating on a flat dark navy void. Sharp pixel edges, chunky 8-bit colour blocking, no text.",
  },
  {
    key: "world_subway_car",
    category: "prop",
    aspectRatio: "16:9",
    subject:
      "Side-on pixel-art of a single sleek subway CAR for an animation loop: rounded brushed-steel body with a continuous cyan window strip, hot-pink stripe along the lower flank, twin headlights glowing white, a roundel logo on the nose, faint motion-blur speed lines behind it. Isolated, centred, floating on a flat dark navy void. Sharp pixel edges, chunky 8-bit colour blocking, no text.",
  },
  {
    key: "world_tile_road",
    category: "prop",
    aspectRatio: "1:1",
    subject:
      "Seamless top-down pixel-art texture tile of a clean asphalt ROAD: dark charcoal asphalt with subtle aggregate speckle, a single dashed lane line in faded hot-pink down the centre, faint cyan-reflective wet sheen, edges that tile seamlessly on all four sides. Flat overhead view, fills the entire frame, no perspective, no objects, no text.",
  },
  {
    key: "world_tile_road_cracked",
    category: "prop",
    aspectRatio: "1:1",
    subject:
      "Seamless top-down pixel-art texture tile of a CRUMBLING ROAD on the edge of the ruined zone: fractured asphalt breaking apart into rubble and potholes, weeds pushing through cracks, a faint sickly green poison-haze creeping in from one corner, the lane line broken and fading. Flat overhead view, fills the entire frame, no perspective, no objects, no text.",
  },
  {
    key: "world_tile_ground",
    category: "prop",
    aspectRatio: "1:1",
    subject:
      "Seamless top-down pixel-art texture tile of bare CITY GROUND: dark cracked concrete paving slabs with thin grout lines, scattered grit, occasional faint pink neon reflection, edges that tile seamlessly on all four sides. Flat overhead view, fills the entire frame, no perspective, no objects, no text.",
  },
  {
    key: "world_tile_intersection",
    category: "prop",
    aspectRatio: "1:1",
    subject:
      "Seamless top-down pixel-art texture tile of a four-way ROAD INTERSECTION centre: charcoal asphalt with painted hot-pink pedestrian crossing stripes on all four sides and a faint cyan box-junction grid in the middle, manhole cover slightly off-centre. Flat overhead view, fills the entire frame, no perspective, no text.",
  },

  // ── Pixel Agent division team banners (wide 16:9 hero strips) ──────────────
  // One per division on the "Meet the Pixel Agents" page. Each shows the team
  // of identical steel pixel-robots at work in their domain, tinted by the
  // division accent. Subjects are kept wide and cinematic for banner crops.
  {
    key: "team_core",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a CORE COMMAND deck: a squad of identical steel pixel-robots with glowing emerald-green eyes standing around a central holographic command table that projects a green wireframe city, giant wall of green status monitors behind them, a robed boss-robot gesturing at the centre. Emerald (#34d399) rim light and signage glow dominating the scene. Heroic, busy, commanding.",
  },
  {
    key: "team_automation",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a GROWTH & AUTOMATION lab: steel pixel-robots with violet eyes tending a wall of glowing pipes, conveyor belts and automated funnel machines pumping violet light, floating growth-graph holograms trending up, server racks. Violet (#a78bfa) rim light and glow dominating. Energetic, mechanical, flowing.",
  },
  {
    key: "team_business",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a BUSINESS DEVELOPMENT war-room: steel pixel-robots with amber eyes around a deal table shaking hands over glowing amber contracts, a handshake hologram, pipeline boards and growth maps on the walls. Warm amber-gold (#fbbf24) rim light and glow dominating. Confident, corporate, dealmaking.",
  },
  {
    key: "team_finance",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a FINANCE DESK trading floor: steel pixel-robots with lime-green eyes at a bank of monitors covered in candlestick charts and ticker tape, stacks of glowing coins and gold bars, a giant lime stock-graph wall. Lime-green (#a3e635) rim light and glow dominating. Fast, money-charged, analytical.",
  },
  {
    key: "team_creative",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a CREATIVE STUDIO: steel pixel-robots with hot-pink eyes at easels and tablets painting glowing canvases, a music robot at a synth, floating brushes and colour swatches, a sculpture in progress. Hot-pink (#f472b6) rim light and glow dominating. Playful, vivid, artistic.",
  },
  {
    key: "team_professional",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a LEGAL & PROFESSIONAL chamber: steel pixel-robots with indigo eyes in tiny ties at a long oak table stacked with glowing legal documents and a brass scale of justice hologram, law-book shelves behind. Indigo (#818cf8) rim light and glow dominating. Formal, serious, authoritative.",
  },
  {
    key: "team_ecommerce",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a COMMERCE FLOOR warehouse: steel pixel-robots with rose eyes packing glowing parcels on conveyor belts, shelves of products, a giant shopping-cart hologram and floating storefront screens. Rose (#fb7185) rim light and glow dominating. Bustling, retail, logistical.",
  },
  {
    key: "team_trades",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a TRADES & SERVICE depot: steel pixel-robots with orange eyes in hard hats wielding wrenches and welding torches over machinery, a service van, toolboxes and glowing orange sparks flying. Orange (#fb923c) rim light and glow dominating. Industrial, hands-on, gritty.",
  },
  {
    key: "team_publishing",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a PUBLISHING HOUSE newsroom: steel pixel-robots with sky-blue eyes at typewriters and printing presses spitting glowing pages, floating headlines and book stacks, a giant printing drum. Sky-blue (#38bdf8) rim light and glow dominating. Literary, busy, ink-and-paper.",
  },
  {
    key: "team_education",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of THE ACADEMY classroom: steel pixel-robots with cyan eyes at desks facing a glowing cyan chalkboard covered in diagrams, a teacher-robot pointing, floating graduation caps and open books. Cyan (#22d3ee) rim light and glow dominating. Scholarly, bright, instructional.",
  },
  {
    key: "team_productivity",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of an OPS & PRODUCTIVITY hub: steel pixel-robots with teal eyes at standing desks juggling glowing task cards on a giant kanban board, calendars and checklists floating, a clockwork wall. Teal (#2dd4bf) rim light and glow dominating. Organised, efficient, in-motion.",
  },
  {
    key: "team_healthcare",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a HEALTH BAY clinic: steel pixel-robots with red eyes in tiny scrubs around a glowing red heartbeat-monitor hologram and a patient pod, IV stands and medicine shelves. Soft red (#f87171) rim light and glow dominating. Caring, clinical, calm.",
  },
  {
    key: "team_personal",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a LIFESTYLE lounge: steel pixel-robots with purple eyes relaxing in a stylish apartment — one cooking, one with a yoga mat, one planning a trip on a glowing map, plants and warm lamps. Purple (#c084fc) rim light and glow dominating. Cozy, personal, aspirational.",
  },
  {
    key: "team_insurance",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of an INSURANCE WING office: steel pixel-robots with blue eyes behind a long desk under a giant glowing blue shield hologram, policy folders and risk-graph screens, an umbrella icon floating. Blue (#60a5fa) rim light and glow dominating. Protective, dependable, institutional.",
  },
  {
    key: "team_gaming",
    category: "ui",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic isometric pixel-art of a GAME WORLD arcade: steel pixel-robots with bright-green eyes at neon arcade cabinets and a giant pixel-game screen, joysticks and floating power-up icons, confetti of pixels. Bright green (#4ade80) rim light and glow dominating. Fun, electric, playful.",
  },

  // ── LANDING — the salaryman's life cinematic (birth → work → death) ────────
  // Wide, wordless scene frames for the scroll-driven public landing page —
  // the FIRST thing every logged-out visitor sees. Each frame is a single
  // moment in one corporate life. These render through the default backend
  // (Nano Banana) so the public front door never depends on an optional /
  // unconfigured render node. No text in any frame — the page is 100% visual;
  // meaning is carried by the imagery alone.
  {
    key: "life_birth",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic scene of a newborn baby cradled in a hospital delivery room at night, swaddled in a pale blanket, tiny and fragile under a single warm overhead lamp. A heart-rate monitor glows cyan beside the bassinet. Hot-pink neon city light bleeds faintly through a window in the background. Soft, hopeful, the very first breath of a life. Cyberpunk noir pixel-painting, deep navy shadows, cinematic, no text.",
  },
  {
    key: "life_childhood",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic scene of a small child playing alone on the floor of a dim apartment, stacking toy blocks into a little tower, a glowing television casting cyan light across the room, a single window showing a hot-pink neon skyline outside. Innocent, quiet, a childhood spent indoors under city light. Cyberpunk noir pixel-painting, deep navy shadows, cinematic, no text.",
  },
  {
    key: "life_school",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic scene of a lone teenage student at a desk in an empty classroom late at night, hunched over textbooks under a cold fluorescent strip light, a chalkboard covered in faded equations behind, a clock on the wall reading past midnight, hot-pink neon glow seeping through tall windows. Studious, exhausted, preparing for a future of work. Cyberpunk noir pixel-painting, deep navy shadows, cinematic, no text.",
  },
  {
    key: "life_first_job",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic scene of a young salaryman in a crisp new suit standing nervously at the threshold of a vast corporate office floor for the first time, briefcase in hand, endless rows of identical desks stretching into haze before him, hot-pink and cyan neon strip lighting overhead, a towering glass window showing the city. Hopeful, dwarfed by the machine he is about to join. Cyberpunk noir pixel-painting, deep navy shadows, cinematic, no text.",
  },
  {
    key: "life_work_prime",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic scene of a salaryman in his prime at his desk in a dense corporate bullpen, suit jacket on the chair, sleeves rolled up, typing intently at a glowing computer monitor, stacks of paper and a cold coffee beside him, identical workers blurred in rows around him, hot-pink and cyan fluorescent glow. The peak of productivity, fully absorbed by the grind. Cyberpunk noir pixel-painting, deep navy shadows, cinematic, no text.",
  },
  {
    key: "life_burnout",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic scene of an aging salaryman alone at his desk in the dead of night, the only light left on in a darkened office floor, slumped and grey-haired, shoulders heavy, staring blankly at a glowing monitor, an avalanche of paperwork around him, a single dead potted plant on the desk. Hot-pink neon from the empty city beyond the window. Worn down, the long erosion of a working life. Cyberpunk noir pixel-painting, deep navy shadows, cinematic, no text.",
  },
  {
    key: "life_death",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic scene of an empty office chair pushed back from a desk where a salaryman once sat, the monitor dark, a coffee mug gone cold, a suit jacket still draped over the chair, a single wilted flower laid on the keyboard. The surrounding desks fade into shadow. A faint pink-and-cyan glow lingers like a departing soul. Solemn, final, a life ended at the desk. Cyberpunk noir pixel-painting, deep navy shadows, cinematic, no text.",
  },
  {
    key: "life_position_open",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic scene of that same now-vacant desk, cleaned and reset, the chair tucked in neatly, the monitor wiped blank and waiting, a fresh nameplate left empty, a soft hot-pink spotlight falling on the open seat as if inviting the next occupant. The rest of the floor recedes into dark. An available position, waiting to be filled. Cyberpunk noir pixel-painting, deep navy shadows, cinematic, no text.",
  },
  {
    key: "life_terminal",
    category: "scene",
    aspectRatio: "16:9",
    subject:
      "Wide cinematic close-up of a single computer terminal sitting on the empty desk in the dark, its screen powered off and black with a faint dormant glow, a chunky power button beside it catching a soft cyan highlight, cables coiling into shadow, hot-pink neon rim light tracing the bezel. Waiting to be switched on. Cyberpunk noir pixel-painting, deep navy shadows, cinematic, no text.",
  },

  // ── Realistic character templates (intake gallery) ────────────────────────
  // Generated from CHARACTER_TEMPLATE_CATALOG so the catalog stays the single
  // source of truth. Realistic style via `fullPrompt`; Unreal-routed with a
  // explicit renderer selection; kickoff fails clearly when that renderer is absent.
  ...characterTemplateKitEntries(),
];

export function getArtKitEntry(key: string): ArtKitEntry | null {
  return SALARYMAN_ART_KIT.find(e => e.key === key) ?? null;
}
