import { Router, type IRouter } from "express";
import healthRouter from "./health";
import openaiRouter from "./openai/index";
import interviewRouter from "./interview";
import toolsRouter from "./tools";
import authRouter from "./auth";
import accountRouter from "./account";
import workspaceRouter from "./workspace";
import planRouter from "./plan";
import stripeRouter from "./stripe";
import worldRouter from "./world";
import profilesRouter from "./profiles";
import salarymanSavesRouter from "./salaryman-saves";
import billboardRouter from "./billboards";
import hiringRouter from "./hiring";
import reportingRouter from "./reporting";
import twilioRouter from "./twilio";
import versionRouter from "./version";
import studioRouter from "./studio";
import storageRouter from "./storage";
import documentsRouter from "./documents";
import calendarRouter from "./calendar";
import aiAgentsRouter from "./ai-agents";
import subscribersRouter from "./subscribers";
import campaignsRouter from "./campaigns";
import seoRouter from "./seo";
import dealsRouter from "./deals";
import goalsRouter from "./goals";
import merchRouter from "./merch";
import cosmeticsRouter from "./cosmetics";
import legalRouter from "./legal";
import contractsRouter from "./contracts";
import salarymanSeasonRouter from "./salaryman-season";
import meetingsRouter from "./meetings";
import investorsRouter from "./investors";
import trialsRouter from "./trials";
import organizationsRouter from "./organizations";
import enterpriseRouter from "./enterprise";
import ticketsRouter from "./tickets";
import feedbackRouter from "./feedback";
import alphaRouter from "./alpha";
import subwayRouter, { seedSubwayStations } from "./subway";
import lifecycleRouter from "./lifecycle";
import addressesRouter from "./addresses";
import botsRouter from "./bots";
import devTasksRouter from "./dev-tasks";
import tradingRouter from "./trading";
import prospectingRouter from "./prospecting";
import chatRouter from "./chat";
import leadsRouter from "./leads";
import insuranceRouter from "./insurance";
import platformApiRouter from "./platform-api";
import adminRouter from "./admin";
import businessOpsRouter from "./business-ops";
import bankRouter from "./bank";
import economyRouter from "./economy";
import cfRouter from "./cf";
import creditRouter from "./credit";
import taxCollectorRouter from "./tax-collector";
import onboardHousingRouter from "./onboard-housing";
import explorationRouter from "./exploration";
import vaultRouter from "./vault";
import mediaRouter from "./media";
import colleaguesRouter from "./colleagues";
import socialMediaRouter from "./social-media";
import marketingConnectionsRouter from "./marketing-connections";
import designStudioRouter from "./design-studio";
import scraperRouter from "./scraper";
import googleLinkRouter from "./google-link";
import pabloFeedRouter from "./pablo-feed";
import pabloCommandRouter from "./pablo-command";
import pabloMemoryRouter from "./pablo-memory";
import pabloCommandsRouter from "./pablo-commands";
import pabloAgentRouter from "./pablo-agent";
import musicRouter from "./music";
import nanoBananaRouter from "./nano-banana";
import realEstateRouter from "./real-estate";
import businessMarketplaceRouter from "./business-marketplace";
import artAssetsRouter from "./art-assets";
import pabloTaxRouter from "./pablo-tax";
import orgWebsiteRouter from "./org-website";
import worldBuildRouter from "./world-build";
import agentProjectsRouter from "./agent-projects";
import pledgeRouter from "./pledge";
import marketingRouter from "./marketing";
import educationRouter from "./education";
import itemsRouter from "./items";
import utilityRouter from "./utility";
import referralsRouter from "./referrals";
import crmRouter from "./crm";
import gameplayTiktokRouter from "./gameplay-tiktok";
import landRouter from "./land";
import autopilotRouter from "./autopilot";
import jobBoardRouter from "./job-board";
import orgAccountsRouter from "./org-accounts";
import skillsRouter from "./skills";
import eventsRouter from "./events";
import resourcesRouter from "./resources";
import servicesRouter from "./services";
import bountiesRouter from "./bounties";
import fleetRouter from "./fleet";
import bankingRouter from "./banking";
import cityVisasRouter from "./city-visas";
import vendingRouter from "./vending";
import gameplayFiatRouter from "./gameplay-fiat";
import gameplayWorldEconomyRouter from "./gameplay-world-economy";
import goldEconomyRouter from "./gold-economy";
import marketplaceRouter from "./marketplace";
import shadowTowerRouter from "./shadow-tower";
import recreationRouter from "./recreation";
import towerMarketRouter from "./tower-market";
import towerLifeRouter from "./tower-life";
import godotRenderRouter from "./godot-render";
import deviceLinksRouter from "./device-links";
import desktopWorkRouter from "./desktop-work";
import businessDataRouter from "./business-data";
import desktopDownloadRouter from "./desktop-download";

const router: IRouter = Router();

router.use(healthRouter);
router.use(versionRouter);
router.use(authRouter);
router.use(openaiRouter);
router.use(interviewRouter);
router.use(toolsRouter);
router.use(accountRouter);
router.use(workspaceRouter);
router.use(planRouter);
router.use(stripeRouter);
router.use(worldRouter);
router.use(profilesRouter);
router.use(salarymanSavesRouter);
router.use(billboardRouter);
router.use(hiringRouter);
router.use(jobBoardRouter);
router.use(studioRouter);
router.use(storageRouter);
router.use(documentsRouter);
router.use(reportingRouter);
router.use(calendarRouter);
router.use(twilioRouter);
router.use(aiAgentsRouter);
router.use(subscribersRouter);
router.use(campaignsRouter);
router.use(seoRouter);
router.use(dealsRouter);
router.use(goalsRouter);
router.use(merchRouter);
router.use(cosmeticsRouter);
router.use(legalRouter);
router.use(contractsRouter);
router.use(salarymanSeasonRouter);
router.use(meetingsRouter);
router.use(investorsRouter);
router.use(trialsRouter);
router.use(organizationsRouter);
router.use(enterpriseRouter);
router.use(ticketsRouter);
router.use(feedbackRouter);
router.use(alphaRouter);
router.use(subwayRouter);
router.use(lifecycleRouter);
router.use(addressesRouter);
router.use(botsRouter);
router.use(devTasksRouter);
router.use(tradingRouter);
router.use(prospectingRouter);
router.use(chatRouter);
router.use(leadsRouter);
router.use(insuranceRouter);
router.use(platformApiRouter);
router.use(adminRouter);
router.use(businessOpsRouter);
router.use(bankRouter);
router.use(economyRouter);
router.use(goldEconomyRouter);
router.use(cfRouter);
router.use(creditRouter);
router.use(taxCollectorRouter);
router.use(onboardHousingRouter);
router.use(explorationRouter);
router.use(vaultRouter);
router.use(mediaRouter);
router.use(colleaguesRouter);
router.use(socialMediaRouter);
router.use(marketingConnectionsRouter);
router.use(designStudioRouter);
router.use(scraperRouter);
router.use(googleLinkRouter);
router.use(pabloFeedRouter);
router.use(pabloCommandRouter);
router.use(pabloMemoryRouter);
router.use(pabloCommandsRouter);
router.use(pabloAgentRouter);
router.use(musicRouter);
router.use(nanoBananaRouter);
router.use(landRouter);
router.use(realEstateRouter);
router.use(businessMarketplaceRouter);
router.use(artAssetsRouter);
router.use(pabloTaxRouter);
router.use(orgWebsiteRouter);
router.use(worldBuildRouter);
router.use(agentProjectsRouter);
router.use(pledgeRouter);
router.use(marketingRouter);
router.use(educationRouter);
router.use(itemsRouter);
router.use(utilityRouter);
router.use(referralsRouter);
router.use(crmRouter);
router.use(gameplayTiktokRouter);
router.use(autopilotRouter);
router.use(jobBoardRouter);
router.use(orgAccountsRouter);
router.use(skillsRouter);
router.use(eventsRouter);
router.use(resourcesRouter);
router.use(servicesRouter);
router.use(bountiesRouter);
router.use(fleetRouter);
router.use(bankingRouter);
router.use(cityVisasRouter);
router.use(vendingRouter);
router.use(gameplayFiatRouter);
router.use(gameplayWorldEconomyRouter);
router.use(shadowTowerRouter);
router.use(recreationRouter);
router.use(towerMarketRouter);
router.use(towerLifeRouter);
router.use(godotRenderRouter);
  router.use(deviceLinksRouter);
  router.use(desktopWorkRouter);
  router.use(businessDataRouter);
  router.use(marketplaceRouter);
  router.use(desktopDownloadRouter);

export default router;
