// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/salaryman-gameplay-tour/SalarymanGameplayTour.tsx": () => import("../components/mockups/salaryman-gameplay-tour/SalarymanGameplayTour.tsx"),
  "./components/mockups/salaryman-professional-home/ProfessionalHome.tsx": () => import("../components/mockups/salaryman-professional-home/ProfessionalHome.tsx")
};
