import { pgTable, serial, varchar, text, timestamp, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

/**
 * Cached Salaryman art assets generated by Nano Banana.
 *
 * Each entry corresponds to one ArtKitEntry from lib/salaryman-art.ts.
 * The asset is generated lazily the first time anyone requests it via
 * /api/art/asset/:key. Subsequent reads are cached forever (we keep the
 * CDN URL apipass returns) until an admin regenerates it.
 */
export const artAssetsTable = pgTable("art_assets", {
  id: serial("id").primaryKey(),
  key: varchar("key", { length: 80 }).notNull().unique(),
  category: varchar("category", { length: 32 }).notNull(),
  subject: text("subject").notNull(),
  prompt: text("prompt").notNull(),
  aspectRatio: varchar("aspect_ratio", { length: 16 }).notNull().default("1:1"),
  url: text("url"),
  status: varchar("status", { length: 16 }).notNull().default("pending"), // 'pending' | 'ready' | 'failed'
  taskId: varchar("task_id", { length: 64 }),
  failMsg: text("fail_msg"),
  // Render-recipe hint for backends that support it (only the Unreal node honors
  // it): 'object' | 'landscape' | 'cinematic'. Null for ordinary still assets.
  jobType: varchar("job_type", { length: 16 }),
  // Whether the finished asset is a still image or a video/sequence. Defaults to
  // 'image' so every existing row and hosted-backend asset is unchanged.
  mediaType: varchar("media_type", { length: 16 }).notNull().default("image"),
  // Which generation backend (provider id) baked / is baking this asset.
  // Defaults to the original Nano Banana behavior so existing rows are unchanged.
  backend: varchar("backend", { length: 32 }).notNull().default("nano-banana"),
  // Provider-specific handle data (JSON) needed to poll an in-flight job — e.g.
  // fal.ai status/response queue URLs. Nano Banana only needs task_id so this
  // stays null for it. Kept generic so a future remote render node can stash its
  // own poll handle here without another schema change.
  backendMeta: text("backend_meta"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  byCategory: index("art_assets_category_idx").on(t.category),
  byStatus: index("art_assets_status_idx").on(t.status),
}));

export const insertArtAssetSchema = createInsertSchema(artAssetsTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertArtAsset = z.infer<typeof insertArtAssetSchema>;
export type ArtAsset = typeof artAssetsTable.$inferSelect;
